version: "3.4"

services:
  dotobot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "9139:9139"
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    depends_on:
      - dotobot-redis
    networks:
      - redis_network

  dotobot-redis:
    image: "redis:alpine"
    container_name: dotobot-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
